<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>EventWeekly demo v1.0</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../css/jquery.mobile-1.2.1.min.css" />
    <link rel="stylesheet" href="../css/blocks.css" />

    <script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyBmhn9fnmPJSCXhztoLm9TR7Lln3bTpkcA&sensor=false"></script>
    <script src="../js/jquery-1.8.3.min.js"></script>

    <script src="../js/jquery.mobile-1.2.1.min.js"></script>
    <!--<script src="../js/fb.js"></script>-->
    <script src="../js/demo_v1.js"></script>

</head>
<body>

