<div data-role="page" id="page1">
<div data-theme="b" data-role="header">
    <span class="ui-title">EventWeekly Demo v1.0</span>
</div>
<div data-role="content">
    <div data-role="navbar" data-iconpos="top">
        <ul>
            <li><a href="Login" data-transition="fade" rel="external">Login</a></li>
            <li><a href="Profile" data-transition="fade" rel="external">Profile</a></li>
            <li><a href="Events" data-transition="fade" rel="external">Events</a></li>
            <li><a href="Map" data-transition="fade" rel="external" id="map_tab">Map</a></li>
        </ul>
    </div>



