<?php include('../app/views/header.phtml'); ?>
<?php include('../app/views/menu.phtml'); ?>

<div class="block">
  <?php if (!empty($event['name'])): ?>
    <h3>Name: <?php echo $event['name'] ?></h3>
  <?php endif; ?>
<div class="ui-grid-a">
    <div class="ui-block-a">
      <?php if (!empty($event['pic_square'])): ?>
        <div><?php echo "<img src=".$event['pic_square'].">" ?></div>
      <?php endif; ?>
    </div>
    <div class="ui-block-b">
        <a data-role="button" id="event_going" href="#page1">Going</a>
        <a data-role="button" id="event_maybe" href="#page1">Maybe</a>
        <a data-role="button" id="event_decline" href="#page1">Decline</a>
        <a data-role="button" id="event_share" href="#page1">Share</a>
    </div>
</div>
  <?php if (!empty($event['description'])): ?>
    <div>Description:<pre><?php echo $event['description'] ?></pre></div>
  <?php endif; ?>
  <?php if (!empty($event['location'])): ?>
    <div>Location:<?php echo $event['location'] ?></div>
  <?php endif; ?>
  <?php if (!empty($event['venue'])): ?>
    <div>Venue:<pre><?php var_dump($event['venue']) ?></pre></div>
  <?php endif; ?>
  <?php if (!empty($event['start_time'])): ?>
    <div>Start time:<?php echo $event['start_time'] ?></div>
  <?php endif; ?>
  <?php if (!empty($event['end_time'])): ?>
    <div>End time:<?php echo $event['end_time'] ?></div>
  <?php endif; ?>
  <?php if (!empty($event['update_time'])): ?>
    <div>Update time:<?php echo $event['update_time'] ?></div>
  <?php endif; ?>
</div>


</div>
</div>

<?php include('../app/views/footer.phtml'); ?>