<?php include('../app/views/header.phtml'); ?>
<?php include('../app/views/menu.phtml'); ?>

<?php if (!empty($events)): ?>
    <div data-role="collapsible-set">

        <div class="block">
          <div>Own events:</div>
          <?php if (count($events[0])>0): ?>
            <?php foreach($events[0] as $event): ?>
              <div data-role="collapsible" data-content-theme="a" data-collapsed="true">
                  <h3><?php echo $event['name'] ?></h3>
                  <img src="<?php echo $event['pic_square'] ?>">
                  <?php echo $event['anon'].'...' ?>
                  <div class="ui-grid-b">
                      <div class="ui-block-a">
                      </div>
                      <div class="ui-block-b">
                          <form method="POST" action="Event" data-ajax="false">
                              <input type="hidden" value="<?php echo $event['eid'] ?>" name="eventId">
                              <input type="submit" value="More...">
                          </form>
                          <!--<a data-role="button" rel="external" href="">More...</a>-->
                      </div>
                      <div class="ui-block-c">
                      </div>
                  </div>
              </div>
            <?php endforeach; ?>
          <?php else: ?>
              <div>Not found<div>
          <?php endif; ?>
        </div>

        <div class="block">
          <div>Friend events:</div>
          <?php if (count($events[1])>0): ?>
          <?php foreach($events[1] as $event): ?>
                <div data-role="collapsible" data-content-theme="a" data-collapsed="true">
                    <h3><?php echo $event['name'] ?></h3>
                    <img src="<?php echo $event['pic_square'] ?>">
                    <?php echo $event['anon'].'...' ?>
                    <div class="ui-grid-b">
                        <div class="ui-block-a">
                        </div>
                        <div class="ui-block-b">
                            <form method="POST" action="Event" data-ajax="false">
                                <input type="hidden" value="<?php echo $event['eid'] ?>" name="eventId">
                                <input type="submit" value="More...">
                            </form>
                            <!--<a data-role="button" rel="external" href="<?php echo "Event/".$event['eid'] ?>">More...</a>-->
                        </div>
                        <div class="ui-block-c">
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
          <?php else: ?>
              <div>Not found<div>
          <?php endif; ?>
        </div>

    </div>
<?php else: ?>
  <div>Login required<div>
<?php endif; ?>



</div>
</div>
<?php include('../app/views/footer.phtml'); ?>