<?php include('../app/views/header.phtml'); ?>
<?php include('../app/views/menu.phtml'); ?>

    <div class="ui-grid-b">
        <div class="ui-block-a">
        </div>
        <div class="ui-block-b">
            <a data-role="button" id="fb-login">Facebook login</a>
        </div>
        <div class="ui-block-c">
        </div>
    </div>

    <div class="ui-grid-b">
        <div class="ui-block-a">
        </div>
        <div class="ui-block-b">
            <div id="login_message" class="center-text hidden"></div>
        </div>
        <div class="ui-block-c">
        </div>
    </div>
</div>
</div>

<?php include('../app/views/footer.phtml'); ?>